import type { Product, Pain, Use } from './types';
import photos from './catalog-images.json';
const base = { bg:'#f4f4f2', price:0, list:0, priceKnown:false, rate:0, revs:0, stock:0, stockTracked:false, availability:'in_stock' as const, flag:'', warr:'3 meses de garantía contra defectos de fábrica desde la entrega. Consulta las condiciones y exclusiones en nuestra política de cambios.', sources:[] };
export const PRODUCTS: Product[] = [
{ ...base, id:'lenovo-xt80', cat:'Audio deportivo', art:'buds', short:'Lenovo XT80', name:'Lenovo XT80 — audífonos deportivos', price:69.99, priceKnown:true, images:photos['lenovo-xt80'], video:'/products/lenovo-xt80/video.mp4', claim:'Un ajuste firme para acompañar tus entrenamientos.', description:'Audífonos inalámbricos con ganchos de sujeción para correr, caminar o entrenar. Su estuche permite guardarlos y recargarlos entre sesiones. Controla tu música y atiende llamadas desde los auriculares.', ben:['Ganchos de sujeción alrededor de la oreja','Controles de música, volumen y llamadas','Estuche para guardar y recargar'], specs:{'Diseño':'Inalámbricos con gancho deportivo','Conexión':'Bluetooth','Autonomía declarada':'Hasta 7 horas por carga, según proveedor','Carga declarada':'Aproximadamente 1.5 horas','Resistencia declarada':'IPX5 según proveedor; no aptos para nadar'}, compat:'Equipos con audio Bluetooth. Confirma versión y accesorios del lote.', note:'Precio del archivo local. Autonomía e IPX5 declarados por el proveedor; no se encontró ficha oficial del lote. No se afirma cancelación activa ni autenticidad certificada.' },
{ ...base, id:'acuaticos-x7', price:149, priceKnown:true, cat:'Audio acuático', art:'swim', short:'POLVCDG X7', name:'POLVCDG X7 — conducción ósea IPX8', images:photos['acuaticos-x7'], claim:'Lleva tu música a la piscina sin llevar el celular.', description:'Auriculares de conducción ósea POLVCDG X7 para natación, running y fitness. Su diseño de oído abierto y banda trasera deja libre el canal auditivo. Guarda música en sus 32 GB de memoria y utiliza el modo MP3 para nadar; fuera del agua, conecta tu teléfono por Bluetooth 5.3 para escuchar música y atender llamadas con el micrófono integrado.', ben:['32 GB de memoria para escuchar música sin celular','Conducción ósea con diseño de oído abierto','Resistencia IPX8 para natación, según el manual','Bluetooth 5.3 y micrófono para llamadas fuera del agua'], specs:{'Marca y modelo':'POLVCDG X7','Color':'Negro / rojo','Tecnología':'Conducción ósea, oído abierto y banda trasera','Memoria interna':'32 GB, según ficha del proveedor','Conectividad':'Bluetooth 5.3 y reproducción local MP3','Resistencia al agua':'IPX8; respetar las condiciones de uso del manual','Autonomía declarada':'Hasta 10 horas al 65 % de volumen','Batería':'200 mAh','Carga':'Magnética; aproximadamente 2 horas','Formatos de música':'MP3, WMA, WAV, APE y FLAC','Controles':'Botones de reproducción, volumen y llamadas','Micrófono':'Integrado para llamadas Bluetooth fuera del agua','Impedancia declarada':'16 Ω, según ficha del proveedor'}, compat:'Teléfonos y equipos compatibles con audio Bluetooth. Para nadar, utiliza música almacenada en la memoria interna y el modo MP3: la conexión Bluetooth no es adecuada bajo el agua. Transfiere archivos desde una computadora mediante el cable magnético de datos.', sources:[{title:'POLVCDG — manual de usuario X7',url:'https://ae01.alicdn.com/kf/S19a2caf352004b809c294076974039c19.pdf'}], note:'Marca, color y capacidad de 32 GB confirmados con la ficha facilitada por el propietario. Bluetooth, IPX8, batería, carga y formatos contrastados con el manual X7. La autonomía depende del volumen y del uso. Enjuaga con agua dulce tras el uso en agua salada y seca el puerto de carga antes de cargar. Consulta los límites de inmersión del equipo.' },
{ ...base, id:'erazer-xf21', stock:0, stockTracked:true, availability:'out_of_stock', cat:'Audio deportivo', art:'buds', short:'ERAZER XF21', name:'ERAZER XF21 — audífonos de oído abierto', images:photos['erazer-xf21'], claim:'Música y llamadas en un formato abierto.', description:'Audífonos inalámbricos ERAZER con formato de oído abierto y estuche de carga. Una alternativa para tus actividades diarias sin introducir almohadillas en el canal auditivo.', ben:['Formato de oído abierto','Estuche para guardar y recargar','Audio y llamadas mediante Bluetooth'], specs:{'Modelo en carpeta':'XF21','Diseño':'Oído abierto con sujeción','Conexión':'Bluetooth; versión por confirmar','Autonomía y resistencia':'Confirmar con el manual del lote'}, compat:'Equipos con audio Bluetooth. Confirma el modelo exacto y sus controles.', note:'El documento local menciona X9 y XF21 en el mismo texto. Se omiten cifras de batería, resistencia y latencia hasta resolver esa discrepancia.' },
{ ...base, id:'haylou-rs4-plus', price:120, priceKnown:true, cat:'Smartwatches', art:'watch', short:'Haylou RS4 Plus', name:'Haylou RS4 Plus — AMOLED de 1.78″', images:photos['haylou-rs4-plus'], claim:'Pantalla fluida y 105 modos para tus entrenamientos.', description:'Reloj inteligente con pantalla rectangular AMOLED de 60 Hz. Registra actividad, frecuencia cardíaca, SpO₂ y sueño, y permite personalizar la esfera. La autonomía depende de las funciones activadas y del uso.', ben:['Pantalla AMOLED con refresco de 60 Hz','105 modos de entrenamiento','Seguimiento de pulso, SpO₂ y sueño'], specs:{'Pantalla':'AMOLED de 1.78″, 368 × 448 píxeles','Refresco':'60 Hz','Modos deportivos':'105','Autonomía':'Hasta 10 días de uso diario; 28 días en uso básico','Monitoreo':'Frecuencia cardíaca, SpO₂ y sueño','Esferas':'Más de 100 opciones'}, compat:'App Haylou Fun en un teléfono compatible. Las mediciones de bienestar son orientativas.', sources:[{title:'Haylou — presentación oficial del RS4 Plus',url:'https://haylou.com/pt/blogs/news/haylou-rs4-plus-debuts-full-screen-with-huge-impact'}], note:'Identificado como RS4 Plus en el texto local; confirma que la caja corresponda a esa versión. La carpeta se llama RS4.' },
{ ...base, id:'zeblaze-stratos-2-ultra', price:200, priceKnown:true, cat:'Smartwatches', art:'watch', short:'Stratos 2 Ultra', name:'Zeblaze Stratos 2 Ultra — GPS deportivo', images:photos['zeblaze-stratos-2-ultra'], claim:'Tus rutas, desniveles y entrenamientos, directo en la muñeca.', description:'Reloj deportivo con GPS de doble frecuencia, brújula, altímetro y más de 170 modos para acompañarte dentro y fuera de la ciudad.', ben:['GPS de doble frecuencia y seis sistemas de satélites','Más de 170 modos deportivos','Brújula y altímetro barométrico'], specs:{'Posicionamiento':'Doble frecuencia, seis sistemas de satélites','Deportes':'Más de 170 modos y reconocimiento inteligente','Resistencia':'10 ATM; uso según el manual','Sensores exteriores':'Brújula y altímetro barométrico','Pantalla declarada por proveedor':'AMOLED de 1.43″'}, compat:'El material local indica GloryFitPro; confirma la app mediante el QR del manual. Las mediciones de bienestar son orientativas y no sustituyen una evaluación médica.', sources:[{title:'Zeblaze — Stratos 2 Ultra oficial',url:'https://www.zeblaze.com/products/zeblaze-stratos-2-ultra'}] },
{ ...base, id:'blackview-bv200', price:280, priceKnown:true, cat:'Lentes inteligentes', art:'glasses', short:'Blackview BV200', name:'Blackview BV200 — lentes inteligentes', images:photos['blackview-bv200'], video:'/products/blackview-bv200/video.mp4', claim:'Cámara Sony de 8 MP y llamadas desde tus lentes.', description:'Lentes inteligentes Blackview BV200 con cámara Sony de 8 MP, llamadas Bluetooth y traducción por voz mediante servicios de inteligencia artificial. Captura momentos desde tu punto de vista y utiliza funciones de audio desde una montura negra de estilo clásico. Confirma los idiomas y las condiciones de los servicios conectados antes de comprar.', ben:['Cámara Sony de 8 MP integrada','Llamadas mediante Bluetooth','Traducción por voz con servicios de IA'], specs:{'Modelo':'Blackview BV200','Cámara':'Sony de 8 MP','Llamadas':'Bluetooth','Funciones conectadas':'Asistencia con IA y traducción por voz','Color fotografiado':'Negro','Memoria y batería':'Confirmar capacidad y autonomía del lote'}, compat:'Requiere un teléfono compatible para llamadas y funciones conectadas. Consulta app, idiomas de traducción, conexión a internet y posibles costos de servicios.', sources:[{title:'Blackview — BV200 oficial',url:'https://store.blackview.hk/products/bv200-price'}], note:'Modelo BV200 confirmado por el propietario del catálogo. Cámara, llamadas y traducción contrastadas con la tienda oficial; memoria, autonomía e idiomas pendientes de verificar.' },
{ ...base, id:'microwear-w-ai-3', price:280, priceKnown:true, cat:'Lentes inteligentes', art:'glasses', short:'Microwear W AI 3', name:'Microwear W AI 3 — lentes con cámara', images:photos['microwear-w-ai-3'], video:'/products/microwear-w-ai-3/video.mp4', claim:'Captura momentos desde tu punto de vista.', description:'Lentes inteligentes Microwear W AI 3 con cámara y funciones de audio. El proveedor describe fotos, video, llamadas, música y asistencia de voz. Las funciones conectadas dependen de la app, el teléfono y los servicios disponibles.', ben:['Cámara integrada para fotos y video','Música y llamadas desde la montura','Formato de manos libres'], specs:{'Modelo':'Microwear W AI 3','Funciones declaradas':'Foto, video, llamadas y música','Asistencia y traducción':'Confirmar idiomas, app, conexión y costos','Memoria y resolución':'Confirmar con el manual del lote'}, compat:'Confirma la app y su compatibilidad con tu teléfono, así como los servicios de voz y traducción incluidos.', sources:[{title:'Microwear — catálogo oficial W AI 3',url:'https://www.microwear.com/index.php/index/navs'}], note:'El texto local mezcla datos de cámara y pantalla; se omiten cifras de resolución y memoria sin validar.' }
,
{ ...base, id:'proteina-deportiva', price:120, priceKnown:true, bg:'#F0E4CC', cat:'Nutrición deportiva', art:'supplement', short:'ISO Whey 90', name:'Universe Nutrition ISO Whey 90', images:photos['proteina-deportiva'], claim:'Una proteína práctica para después de entrenar, en el sabor que más te guste.', description:'Proteína de suero Universe Nutrition ISO Whey 90 de 1.2 kg, disponible en vainilla y cookies & cream.', ben:['24 g de proteína por porción, según la etiqueta','40 porciones de 30 g','Envase sellado de 1.2 kg'], specs:{'Marca':'Universe Nutrition','Producto':'ISO Whey 90','Contenido neto':'1.2 kg','Porción':'30 g','Proteína declarada':'24 g por porción','Servicios':'40','Sabores':'Vainilla / Cookies & Cream'}, compat:'Contiene proteína de suero de leche. Revisa todos los ingredientes y alérgenos de la etiqueta si sigues una dieta especial o tienes alguna condición de salud.', warr:'Al recibirla, revisa que el sello esté intacto y confirma lote y vencimiento. Por seguridad alimentaria, no podemos cambiar envases abiertos.', note:'Información tomada de las fotografías del envase entregadas por el propietario. Confirma lote, ingredientes y tabla nutricional al recibir.', variants:[{id:'proteina-vainilla',sku:'PROT-VAI',label:'Vainilla',flavor:'Vainilla',swatch:'#F3E5B7',imageIndex:0,stock:3},{id:'proteina-cookies-cream',sku:'PROT-COO',label:'Cookies & Cream',flavor:'Cookies & Cream',swatch:'#D8D1C8',imageIndex:1,stock:1}] },
{ ...base, id:'creatina-monohidratada', price:67, priceKnown:true, bg:'#D9DEE3', cat:'Nutrición deportiva', art:'supplement', short:'Creatina UN', name:'Universe Nutrition 100% Creatine', images:photos['creatina-monohidratada'], claim:'Una opción simple, sin sabor y fácil de sumar a tu rutina.', description:'Creatina monohidratada micronizada Universe Nutrition, sin sabor, en presentaciones de 250 g y 500 g.', ben:['Creatina monohidratada micronizada','Sin sabor','Opciones de 250 g y 500 g'], specs:{'Marca':'Universe Nutrition','Tipo':'Creatina monohidratada micronizada','Sabor':'Sin sabor','Porción declarada':'2.5 g','Presentaciones':'250 g (100 servicios) / 500 g (200 servicios)','Información dietaria declarada':'Vegana, sin gluten y sin lactosa'}, compat:'Producto recomendado para adultos. Sigue la porción indicada en el envase; si tienes una condición médica, estás embarazada o tomas medicamentos, consulta primero a un profesional de salud.', warr:'Al recibirla, revisa que el sello esté intacto y confirma lote y vencimiento. Por seguridad alimentaria, no podemos cambiar envases abiertos.', note:'Marca, contenido y porciones tomados de las fotografías y la descripción entregadas por el propietario. Verifica siempre la etiqueta del lote.', variants:[{id:'creatina-250g',sku:'CREA-250',label:'250 g',size:'250 g',presentation:'100 servicios',swatch:'#D7DCE1',imageIndex:0,stock:2,price:67,priceKnown:true},{id:'creatina-500g',sku:'CREA-500',label:'500 g',size:'500 g',presentation:'200 servicios',swatch:'#BCC4CC',imageIndex:1,stock:2,price:110,priceKnown:true}] },
{ ...base, id:'lentes-torneo', price:50, priceKnown:true, bg:'#EEF2E9', cat:'Natación', art:'goggles', short:'Torneo Competition', name:'Lentes de natación Torneo Competition', images:photos['lentes-torneo'], claim:'Visión clara y un ajuste cómodo para concentrarte en cada largo.', description:'Lentes Torneo Competition con mica espejada, protección UV y tratamiento antiempañante, según el empaque.', ben:['Mica espejada con protección UV','Tratamiento antiempañante','Estuche rígido incluido'], specs:{'Marca':'Torneo','Línea':'Competition','Uso':'Entrenamiento y competencia','Micas':'Espejadas','Protección':'UV Shield, según el empaque','Tratamiento':'Antifog, según el empaque','Incluye':'Estuche rígido'}, compat:'Ajusta la correa hasta lograr un sellado cómodo, sin apretar de más. El calce puede variar según la forma del rostro.', note:'Las características se tomaron del empaque fotografiado y del texto entregado por el propietario. Los colores dependen del stock.', variants:[{id:'torneo-verde',sku:'TOR-VER',label:'Verde',color:'Verde',swatch:'#91D934',imageIndex:0,stock:2},{id:'torneo-azul',sku:'TOR-AZU',label:'Azul',color:'Azul',swatch:'#25A9E0',imageIndex:1,stock:2},{id:'torneo-negro',sku:'TOR-NEG',label:'Negro',color:'Negro',swatch:'#17191B',imageIndex:1,stock:2},{id:'torneo-blanco',sku:'TOR-BLA',label:'Blanco',color:'Blanco',swatch:'#F4F4F2',imageIndex:1,stock:2}] },
{ ...base, id:'gorros-natacion', price:30, priceKnown:true, stock:0, stockTracked:true, availability:'out_of_stock', cat:'Natación', art:'swimcap', short:'Gorros de natación', name:'Gorros de natación', images:[], claim:'Comodidad para entrenar y mantener el cabello recogido en la piscina.', description:'Gorros de natación ligeros, disponibles en colores y materiales según el inventario.', ben:['Pensados para piscina','Fáciles de llevar en la mochila','Colores según disponibilidad'], specs:{'Marca':'Por confirmar','Material':'Por confirmar','Talla':'Por confirmar','Colores':'Según stock'}, compat:'Elige el material y el ajuste que te resulte cómodo. Después de nadar, enjuágalo con agua dulce y déjalo secar a la sombra.', note:'Faltan confirmar marca, material, talla, colores y fotografías del inventario.' }
];
export const PAINS: Pain[] = [
{pain:'¿Qué audífonos no se caen al correr o entrenar?',to:'lenovo-xt80',fix:'Lenovo XT80'},
{pain:'¿Qué audífonos sirven para nadar en piscina?',to:'acuaticos-x7',fix:'Acuáticos X7'},
{pain:'¿Qué proteína tomar después de entrenar?',to:'proteina-deportiva',fix:'ISO Whey 90'},
{pain:'¿Qué smartwatch tiene pantalla AMOLED para entrenar?',to:'haylou-rs4-plus',fix:'Haylou RS4 Plus'},
{pain:'¿Qué lentes inteligentes graban fotos y videos?',to:'microwear-w-ai-3',fix:'Microwear W AI 3'}
];
export const USES: Use[] = [
  {t:'Entrenar',image:'/uses/lucho-entrenar.webp',alt:'Lucho corriendo junto al mar con un smartwatch',n:'9 productos relacionados',href:'/catalogo?uso=entrenar'},
  {t:'Escuchar',image:'/uses/lucho-escuchar-peruanidad.webp',alt:'Lucho con polo Kallpa bordado y audífonos XT80 en un parque inspirado en la avenida de la Peruanidad, Jesús María',n:'3 audífonos',href:'/catalogo?uso=escuchar'},
  {t:'Espiar',image:'/uses/lucho-espiar-card.webp',alt:'Lucho como un agente secreto con lentes inteligentes Blackview',n:'2 lentes inteligentes',href:'/catalogo?uso=espiar'},
];
export const PRODUCT_IDS_BY_USE = {
  entrenar: ['lenovo-xt80', 'acuaticos-x7', 'erazer-xf21', 'haylou-rs4-plus', 'zeblaze-stratos-2-ultra', 'proteina-deportiva', 'creatina-monohidratada', 'lentes-torneo', 'gorros-natacion'],
  escuchar: ['lenovo-xt80', 'acuaticos-x7', 'erazer-xf21'],
  espiar: ['blackview-bv200', 'microwear-w-ai-3'],
} as const;
export const BUNDLES = [] as const;
export const bySlug = (slug:string) => PRODUCTS.find(p => p.id === slug);
export const variantById = (p: Product, variantId?: string) => p.variants?.find(v => v.id === variantId);
export const productPriceKnown = (p: Product, variantId?: string) => variantById(p, variantId)?.priceKnown ?? p.priceKnown;
export const productUnitPrice = (p: Product, variantId?: string) => variantById(p, variantId)?.price ?? p.price;
export const productLineName = (p: Product, variantId?: string) => {
  const variant = variantById(p, variantId);
  return variant ? `${p.short} · ${variant.label}` : p.short;
};
export const otherThan = (slug:string,n=3) => PRODUCTS.filter(p => p.id !== slug).sort((a,b) => Number(b.cat === bySlug(slug)?.cat)-Number(a.cat === bySlug(slug)?.cat)).slice(0,n);
